# === Calendly ===
CALENDLY_PAT = "eyJraWQiOiIxY2UxZTEzNjE3ZGNmNzY2YjNjZWJjY2Y4ZGM1YmFmYThhNjVlNjg0MDIzZjdjMzJiZTgzNDliMjM4MDEzNWI0IiwidHlwIjoiUEFUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2F1dGguY2FsZW5kbHkuY29tIiwiaWF0IjoxNzU1OTUzMTMyLCJqdGkiOiJjZWEyZTI5OC01MmU0LTQxZWMtYWM5Ny0wNzA3YWU3OTIxNWUiLCJ1c2VyX3V1aWQiOiI1MjE4ZTQ2Zi1mMTE0LTQwNGMtYWMwMS0zMzliNDc1ODE1MjkifQ.rj-Uf3svGF-b3ngz6E42Mi16V1U5YLt_SRtxsN5pmqchOLI9bxifn2917XBQB7GWG-0xLsICXR0070jOdENEmw"
# Either paste your Event Type URI (preferred) or leave blank to fall back to the public link.
CALENDLY_EVENT_TYPE = "https://api.calendly.com/event_types/REPLACE_WITH_YOUR_EVENT_TYPE_ID"
CALENDLY_TZ = "America/New_York"
# Optional direct public link fallback (used if EVENT_TYPE is missing)
CALENDLY_URL = "https://calendly.com/<your-handle>/speak-with-a-team-member"
