# ... existing secrets (Calendly, etc.)
GOOGLE_SA_JSON = """
{ ... your service-account.json here ... }
"""
LEADS_SHEET_ID = "1ABCDEF...your_google_sheet_id..."
STUDIO_FROM_EMAIL = "frontdesk@swtfitness.com"  # sender for follow-ups
